### ISSUE TITLE
Navigation stack is empty after call PushPopupPageAsync

### ISSUE THREAD

**Issue by beylkhanovdamir** [dansiegel/Prism.Plugin.Popups#29]
If I make call PushPopupPageAsync method and select an action, so then after navigating to selected page from action, my nav stack is empty (i.e. current nav history will clear)
How it fix?

**Comment by dansiegel** [comment]
@beylkhanovdamir can you provide a little more information on this problem? Do you mean you have something like: `ViewA/PopupPageA/ViewB` and when you navigate back from `ViewB` your stack is just `ViewA` and `PopupPageA` is gone?

**Comment by beylkhanovdamir** [comment]
@dansiegel yes

but now another case already

I've a page where I call a popup.

Then I want to pass a some param from popup back to the page. I'm writing like this ```_navigationService.PopupGoBackAsync("popupKey", "111")```
So how I can catch this go back event on page?

**Comment by dansiegel** [comment]
@beylkhanovdamir this is a limitation of Rg.Plugins.Popup. If you push any new non-Popup Page onto the stack it will automatically clear out any Popup Pages that you may have had. 

You can have `ViewA/PopupPageA/PopupPageB` and call `PopupGoBackAsync` and go back to `PopupPageA`, however as I mentioned there is simply no way to restructure the Popup pages you may have between `ViewA` and `ViewB` as they would have been disposed.

**Comment by beylkhanovdamir** [comment]
@dansiegel 

I've ContentPageA/PopupPageB and I call PopupGoBackAsync and go back to ContentPageA
Why PopupGoBackAsync method is allowing passing params if it not possible as you wrote?

**Comment by dansiegel** [comment]
If the navigation stack is as you describe `ContentPageA/PopupPageB`, then yes you should be able to pass parameters from `OnNavigatingFrom` on `PopupPageB` to `OnNavigatingTo` on `ContentPageA`. What I was saying is that if you Navigated from`PopupPageB` to `ContentPageC` when you go back you would be going back to `ContentPageA` because `PopupPageB` is automatically popped by the PopupNavigationService when you push a normal Xamarin Forms page. If you have a reproduction I'd be happy to take a look at it.
