### ISSUE TITLE
OnNavigateFrom does not fire for background press

### ISSUE THREAD

**Issue by kylewarren** [dansiegel/Prism.Plugin.Popups#40]
After displaying my pop up page, I clicked on background, popup page dismisses, but onNavigateFrom does not fire, nor do the onNavigate methods of the page i'm over laying

**Comment by dansiegel** [comment]
Looks like there is in fact an event handler for this. I believe we can inject a behavior to handle the event.

**Comment by kylewarren** [comment]
Great! Do I need to do anything to help? I'm new to github and not familiar with processes yet.

**Comment by dansiegel** [comment]
Issue #41 really needs to be fixed first. If you have the time and would like to help I am more than happy to accept a PR, but it isn't a requirement. There's a ton of tutorials out there, [here](https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/) is one to get you started since you're new.

**Comment by dansiegel** [comment]
The `BackgroundPopupDismissalBehavior` should help address this issue in pre2
