### ISSUE TITLE
The sample project cannot be built 

### ISSUE THREAD

**Issue by jessejiang0214** [dansiegel/Prism.Plugin.Popups#68]
I have tried Windows and Mac environment, both of them cannot be built

**Comment by dansiegel** [comment]
It builds just fine on AppCenter as well as my Mac and Windows desktop... can't really say what your problem is without knowing your OS/IDE versions... but I can promise it does build just fine.

**Comment by jessejiang0214** [comment]
@dansiegel Can you try or launch the demo. Maybe something wrong with latest VS for Mac, Please.

**Comment by dansiegel** [comment]
@jessejiang0214 the project builds just fine. You've given me no information beyond you can't build it. I purposely have CI set up on this project to ensure that it builds correctly and I actually download the built apps to my devices, so I know it works. The plugin is pretty widely used so whatever the issue is that you're having I doubt the issue lies within the codebase here.
