### ISSUE TITLE
ClearPopupStackAsync or similar

### ISSUE THREAD

**Issue by cassionandi** [dansiegel/Prism.Plugin.Popups#70]
hi @dansiegel !

If ClearPopupStackAsync is deprecated on 2.0, how do I clean the PopUps from stack?

I have a normal Page that opens a PopUp, them User tab and another PopUp opens, when the User selects the options on the PopUp 2, a normal Page opens... so, I need to take all PopUps in front of the last opened Page.

**Comment by dansiegel** [comment]
A couple of things here... 

1. the `ClearPopupStackAsync` extension has not been deprecated.
1. say you have `ViewA/PopupA/PopupB` and you want to navigate to `ViewB`, you simply navigate to ViewB and your navigation stack will be `ViewA/ViewB`. Rg.Plugins.Popup does this automatically when you push any non-popup page.

**Comment by cassionandi** [comment]
It's true, I misread about the `ClearPopupStackAsync`.

I am experiencing the following behavior. 

It all starts with a Absolute URI: `http://minha.url.br/MainPage/NavigationPage/DashboardPage` to open the main page of a MasterDetail.

Then users navigate to 
`await _navigationService.NavigateAsync("ProgramaPage);` to open the first PopUp

He navigates to the second PopUp
`await _navigationService.NavigateAsync("UADisciplinaPage", p);` 

Then he finishs opening an TabbedPage (non-PopUp)
`await _navigationService.NavigateAsync("DetalheTabbedPage?selectedTab=NotasPage", p);`

The PopUps stay in the front of the DetalheTabbedPage (which opens in the background).

**Comment by linnkrb** [comment]
I belive I am experiencing a similar problem, not sure if it is a prism problem or this, but this problem occurred for us when upgrading to prim 7.0 and then moving from  autofac popup extension to this.

We are trying to close two popups in one go as well (they are taking up the whole screen, could that be the problem ?), but it does not seam to work. First of all when I check  the GetNavigationUriPath after I have navigated to the second popup, the first popup is not there (the page is not removed from the screen, because going back directly from there with navigationService.GoBackAsync(); it is still there). Is this correct behaviour ? If I do a ClearPopupStackAsync() it removes the second popup, but not the first from the screen.  navigationService.GoBackAsync(); Has the same effect (of course).
If I try to navigate to another page (as your example @dansiegel ),  none of the popups actually go away from the screen, but they are removed when I test GetNavigationUriPath(). 

In the previous version of Prism,  when popping the second  popuppage I added a parameter to it,  that parameter was sendt to the first popuppage in the onNavigatingTo, and closed it, but now the onNavigatingTo is not triggered (I guess because Prism does not "know" about it (its gone from  
ClearPopupStackAsync() ), so that does not help me either. 

So, I think that the problem is that when going from one popup page to another, the page does not get removed from the screen, but from the navigation stack that Prism holds on to ?

**Comment by linnkrb** [comment]
I have sort of a work around though.
Before I navigate to the other page B, I do
navigatonService.GoBackAsync() (could also do navigatonService.ClearPopupStackAsync())
Witch closes the secondPopup 
and then in my other page B
in the onNavigatingTo  (this is not a popup) I do a navigatonService.ClearPopupStackAsync()

So I actaully have to call navigatonService.ClearPopupStackAsync() twice it seams like

**Comment by dansiegel** [comment]
@linnkrb your issue sounds like you forgot to register the PopupNavigationService. In 1.0 of the Plugin, all of the Navigation calls were extension methods. Now the only extension is the ClearPopupStack... If your PopupPages are taking up the full screen then it sounds like they've been pushed as a normal ContentPage which would happen if you didn't call the `RegisterPopupNavigationService` in your `App.RegisterTypes`.

**Comment by linnkrb** [comment]
I register
containerRegistry.RegisterPopupNavigationService();
and this particular popups are fullscreen by choice, -mainly because of the previous lack of removing a page in the midle of the stack. I´m thinking I should probably refacor this though, but I have other places it would be useful to remove all popups, not only just the last one.

**Comment by linnkrb** [comment]
I see that with all my popups I do  
containerRegistry.RegisterForNavigation<PaymentMenuPopupPage, PaymentPopupMenuViewModel>(PageConstants.PaymentMenu);   I haven't used autowiring for any of my navigation pages or popup pages, could this be the reason why it is not working as expected ? I see in your example (and the awesome prism template) that you are not registering the popup any where in the app.xaml.cs 
When I think of it, it seams weird toRegisterForNavigation when it is not for navigation, but is there anyway to wire popups ? I have so many pages that I have structured things in folders to easier find stuff and would like to stick to that...
