### ISSUE TITLE
Popup won't close on navigation

### ISSUE THREAD

**Issue by cassionandi** [dansiegel/Prism.Plugin.Popups#73]
Hi!

Is this the correct behavior when you navigate to another page from a Popup? The page behind the popup chances, but the popup keep in front.

![Image of the App](https://media.giphy.com/media/T9ISgAVDkQeBV4iPym/giphy.gif)

**Comment by dansiegel** [comment]
can you provide a simple reproduction app

**Comment by cassionandi** [comment]
I will try to strip down my work-in-progress app and provide you a sample.

**Comment by Jaguel** [comment]
Hi.

**Comment by Jaguel** [comment]
Hi . 

This happens when we want to navigate to a normal page from a PopupPage. The new page shows up but the PopupPage is still open and actually PopupPage is not part of NavigationStack. 

BTW I tested the same scenario with normal navigation (not prism INavigationService) and I still get the same behavior. 

I created a very simple app that produces this issue [https://github.com/Jaguel/PrismPopupNavigationTest](url)

**Comment by dansiegel** [comment]
@jaguel thanks for providing a sample. I’ll look into this, this week.

**Comment by cassionandi** [comment]
thanks for the sample @Jaguel. Sorry for the delay @dansiegel .

**Comment by REXiator** [comment]
@dansiegel Any ETA on this? Currently I have to make awkward workarounds, navigating back to the previous (non-popup) page with custom parameters and have the (non-popup) page perform the actual navigation if said parameters are found in the NavigationParameters. Would love to get rid of that ugly code.

**Comment by torturegenitale** [comment]
I solved this issue like this : 
`await NavigationService.NavigateAsync("MyTargetedContentPage"); //Navigate away from the popup
            await NavigationService.ClearPopupStackAsync(); //Close the current popup`
